### ISSUE TITLE
php 7

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/piwik#1]
Ich wollte es mal testen aber ich bekam diese Meldung ;-)

AddOn piwik konnte aus folgendem Grund nicht installiert werden:
Die PHP-Version (7.1.1) entspricht nicht der geforderten Versionsbedingung ^5.6!

**Comment by schuer** [comment]
@gseilheimer Die Notation für PHP — anders als die Notation für andere Dependencies — sollte lieber so sein: `php: '>=5.6'`. Damit bleibt es nicht auf 5 beschränkt.

Beim Cache-Warmup hatten wir das neulich mal durchgespielt, auch das Thema `conflicts`, von dem kaum jemand weiß. Als Anregung also: https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/package.yml

**Comment by gseilheimer** [comment]
Danke. Geändert. Letzten Stand in MyREX eingetragen.
=> die hinterlegte URL in MyRedaxo ändert die Dateien nicht dynamisch...
