### ISSUE TITLE
Vorteile?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/piwik#2]
Im Moment macht dieses Addon doch nichts anderes, als einen Button zu liefern, der ein Template einfügt, das ich von Hand anpassen muss (ID, etc.)

Das ist ja mehr Aufwand, als den Code einfach von Piwik zu kopieren und in ein Template einzufügen. Die Sinnhaftigkeit des Addons erschließt sich mir daher nicht.

**Comment by skerbis** [comment]
@alexplusde In der Readme steht doch, dass Du Wünsche äußern kannst. Was wünschst Du Dir denn?

**Comment by gseilheimer** [comment]
@alexplusde Defecto hast Du recht mit dem vorliegenden Code. Was wäre dein Vorschlag oder Wunsch?

**Comment by AWqxKAWERbXo** [comment]
War nicht böse gemeint, oder so. Ich war nur verdutzt. So hätte ich mir das Addon vor dem Installieren vorgestellt

* automatische Einbindung per OutputFilter
* Eingabe direkt im Addon
* wenn schon, denn schon: Eingabefelder für weitere Tracking-Codes (Facebook-Pixel, Google Analytics, etc.)

Weitere Ideen:
*Ausgabe einer Basis-Besuchsauswertung für Redakteure
* Ausgabe von statistischen Daten direkt am Artikel

**Comment by skerbis** [comment]
ich sehe eher eine Lösung, das das alte PIWIK-AddOn für REX 4 ersetzt. 
- Einbindung des Tracking-Codes anhand der Side-ID
- Ausgabe nützlicher Kennwerte anhand der PIWIK-Api

**Comment by AWqxKAWERbXo** [comment]
Da fällt mir noch ein:
* Hinterlegen verschiedener Tracking-Codes pro YRewrite-Domain (dort könnte sich das Addon evtl. auch anheften und zusätzliche Metafelder zur Domain anlegen)

**Comment by skerbis** [comment]
@alexplusde wo wir wieder bei yrewrite-metas wären, die das leicht erledigen könnten.

**Comment by skerbis** [comment]
Habe mich mal mit dem Thema beschäftigt: 
https://github.com/FriendsOfREDAXO/matomo

Ich bin dafür dieses AddOn hier zu archivieren

**Comment by gseilheimer** [comment]
Ja. Gern.
